version: '3'
services:
  angular-app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production