version: '3'
services:
  angular-app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    volumes:
      - .:/app
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
